services:
  webapi:
    build:
      context: .
      dockerfile: 8BallPool.WebAPI/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - postgres
    networks:
      - 8ballpoolnetwork
    restart: on-failure

  postgres:
    image: postgres:17
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: 8ballpooldb
    ports:
      - "5433:5432" 
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - data_protection:/home/app/.aspnet/DataProtection-Keys
    networks:
      - 8ballpoolnetwork

networks:
  8ballpoolnetwork:

volumes:
  postgres_data:
  data_protection: